### ISSUE TITLE
First tasks

### ISSUE THREAD

**Issue by Mavrin** [Mavrin/rss-1#2]
Добавьте комментарием ссылку на первую задачу.

**Comment by AnnYevlakova** [comment]
https://annyevlakova.github.io/positionin_and_floats/

**Comment by MaksNik** [comment]
https://github.com/MaksNik/float-position-task

**Comment by marinovich** [comment]
https://github.com/marinovich/position-and-float

**Comment by gbogdanova** [comment]
https://github.com/gbogdanova/positionin-and-floats

**Comment by SerafimovichEugene** [comment]
https://github.com/SerafimovichEugene/positioning_and_floats

**Comment by DenisMl** [comment]
https://denisml.github.io/positionin_and_floats/

**Comment by ghost** [comment]
https://github.com/AlexeyHrebtov/float_and_position

**Comment by aleksandrOranskiy** [comment]
https://aleksandroranskiy.github.io/Positioning-Floats/

**Comment by MichDreby** [comment]
https://github.com/MichDreby/Positioning-floats-task

**Comment by Supersmf** [comment]
https://github.com/Supersmf/Positionin_And_Floats
