### ISSUE TITLE
Games

### ISSUE THREAD

**Issue by Mavrin** [Mavrin/rss-1#4]
Добавьте ссылку на саму игру и на исходный код.

**Comment by SerafimovichEugene** [comment]
https://serafimovicheugene.github.io/fly-game/
https://github.com/SerafimovichEugene/fly-game

**Comment by Supersmf** [comment]
https://supersmf.github.io/Simple_Game/
https://github.com/Supersmf/Simple_Game

**Comment by MichDreby** [comment]
https://michdreby.github.io/
https://github.com/MichDreby/MichDreby.github.io.git
стрелки контроль, на 'F' удар:)
В среду на презентацию иду с ней. Разрешили доделывать до даты презентации.
Еще добавлю звуки и расширю карту.

**Comment by marinovich** [comment]
https://marinovich.github.io/simple-game/
https://github.com/marinovich/marinovich.github.io

**Comment by aleksandrOranskiy** [comment]
https://aleksandroranskiy.github.io/simpleGame/
https://github.com/aleksandrOranskiy/simpleGame

**Comment by DenisMl** [comment]
https://denisml.github.io/game/
https://github.com/DenisMl/game/tree/master

**Comment by AnnYevlakova** [comment]
https://github.com/AnnYevlakova/catcher
https://github.com/rolling-scopes-school/AnnYevlakova-front-end-course/tree/simple-game
